version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - sphinx-apidoc -o _apidoc ../pytrnsys_process

python:
  install:
    - requirements: requirements/dev.txt

sphinx:
  configuration: doc/conf.py