version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - git lfs pull
      - sphinx-apidoc -o doc/_apidoc pytrnsys_process

python:
  install:
    - requirements: requirements/test.txt

sphinx:
  configuration: doc/conf.py
