name: Release to PyPi
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  tests-and-checks:
    uses: ./.github/workflows/tests-and-checks-linux.yml
  release-pypi:
    needs: tests-and-checks
    uses: ./.github/workflows/release-pypi.yml




