name: Tests and Checks

on:
  push:
    branches: '*'
    # pull_request:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  tests-and-checks-linux:
    uses: ./.github/workflows/tests-and-checks-linux.yml
  tests-and-checks-windows:
    uses: ./.github/workflows/tests-and-checks-windows.yml

