name: tests-and-checks-windows
on:
  workflow_call:

jobs:
  test-windows:
    runs-on:
      - self-hosted
      - spf-windows-gh-runners
    env:
      PY_COLORS: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Remove old venv
        run: |
          if (Test-Path -LiteralPath venv) {
            Remove-Item -LiteralPath venv -Recurse
          }
      - name: Create virtual environment
        run: py -3.12 -m venv venv
      - name: Install dependencies
        run: |
          venv\Scripts\python -m pip install --upgrade pip
          venv\Scripts\python -m pip install wheel
          venv\Scripts\python -m pip install -r requirements/test.txt
      - name: Syntax checking with black
        run: venv\Scripts\python dev-tools/dev_tools.py --black --keep-results
      - name: Static type checking with mypy
        run: venv\Scripts\python dev-tools\dev_tools.py --type
      - name: Lint with pylint
        run: venv\Scripts\python dev-tools\dev_tools.py --lint --keep-results
      - name: Test with pytest
        run: venv\Scripts\python dev-tools\dev_tools.py --unit "not manual and not linux and not tool" --keep-results
      - name: Build documentation
        run: venv\Scripts\python dev-tools\dev_tools.py --doc --keep-results
      - name: Post coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: test-results/coverage.lcov
      - name: Upload test results and coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: pytrnsys-process-build-artifacts-windows
          path: |
            test-results
            doc/_build
