name: Trigger read the docs
on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Read The Docs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: 'random string'
          webhook_token: 'random_string'
          commit_ref: ${{ github.ref }}
